# Generated by Django 2.2.13 on 2020-06-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.FloatField(blank=True, verbose_name='Poids')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modèle')),
                ('immatriculation', models.CharField(blank=True, max_length=200, null=True, verbose_name='immatriculation')),
                ('nb_place', models.IntegerField(blank=True, null=True, verbose_name='Nombre de places')),
                ('etat', models.TextField(blank=True, verbose_name='Etat du véhicule')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.TypeVehicules', verbose_name='Type de véhicules')),
            ],
        ),
    ]
