# Generated by Django 2.2.13 on 2020-06-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicules',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypeVehicules',
        ),
        migrations.DeleteModel(
            name='Vehicules',
        ),
    ]
