# Generated by Django 2.2.13 on 2020-06-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commandes', '0002_auto_20200614_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('assureur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assureur')),
                ('taux', models.FloatField(blank=True, null=True, verbose_name='Taux')),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colis',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=200, null=True, verbose_name='Réference')),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('observation', models.TextField()),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Prix')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Non payé'), (2, 'Payé'), (3, 'En transit'), (4, 'Livré')], null=True)),
                ('modele', models.CharField(blank=True, choices=[('VIP', 'VIP'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], max_length=50, null=True, verbose_name='Modèle envoi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city_arrive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityArrival', to='geolocalisation.City')),
                ('city_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityDepart', to='geolocalisation.City')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.Colis')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='commandes.Insurance')),
            ],
        ),
    ]
