# Generated by Django 2.2.13 on 2020-06-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_auto_20200620_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='colis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.Colis'),
        ),
    ]
