# Generated by Django 2.2.13 on 2020-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20200620_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Taille'),
        ),
    ]
