# Generated by Django 2.2.13 on 2020-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_auto_20200704_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
