# Generated by Django 2.2.13 on 2020-07-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commandes', '0010_remove_colis_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
