# Generated by Django 2.2.13 on 2020-07-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0012_reclamations_reclamationshandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.FloatField(verbose_name='Minimum')),
                ('max_weight', models.FloatField(verbose_name='Maximum')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('commission', models.FloatField(verbose_name='Commission')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colis'),
        ),
        migrations.AlterField(
            model_name='reclamations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reclamations'),
        ),
        migrations.AddConstraint(
            model_name='tranche',
            constraint=models.UniqueConstraint(fields=('min_weight', 'max_weight', 'price'), name='tranche_unique'),
        ),
    ]
