# Generated by Django 2.2.13 on 2020-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0013_auto_20200724_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranche',
            name='commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission'),
        ),
    ]
