# Generated by Django 2.2.13 on 2020-07-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0016_tranche_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='modele',
        ),
        migrations.AddField(
            model_name='commandes',
            name='commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='commandes',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commandes.Package', verbose_name='Package envoie'),
            preserve_default=False,
        ),
    ]
