# Generated by Django 2.2.13 on 2020-07-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0017_auto_20200728_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='max_weight',
            field=models.IntegerField(verbose_name='Maximum'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='min_weight',
            field=models.IntegerField(verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prix'),
        ),
    ]
