# Generated by Django 2.2.13 on 2020-08-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0019_auto_20200801_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('status', models.CharField(blank=True, choices=[('Non payé', 'Non payé'), ('Payé', 'Payé')], max_length=15, null=True, verbose_name='Etat')),
                ('link_facture', models.CharField(max_length=50, verbose_name='Lien facture')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandeFacture', to='commandes.Commandes')),
            ],
        ),
    ]
