# Generated by Django 2.2.13 on 2020-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0021_auto_20200801_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='accepted',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Etat'),
        ),
    ]
