# Generated by Django 2.2.13 on 2020-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0022_commandes_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='accepted',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Accepté'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='reclamations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='reclamations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='reclamationshandler',
            name='type',
            field=models.CharField(blank=True, choices=[('En cours de traitement', 'En cours de traitement'), ('Résolu', 'Résolu'), ('Non résolu', 'Non résolu')], max_length=50, null=True, verbose_name='Action faite'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission'),
        ),
    ]
