# Generated by Django 2.2.13 on 2020-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0023_auto_20200807_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
