# Generated by Django 2.2.13 on 2020-07-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district', to='geolocalisation.City', verbose_name='Ville *'),
        ),
    ]
