# Generated by Django 2.2.13 on 2020-08-24 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenceuser',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_agence', to='agences.Agences'),
        ),
        migrations.AlterField(
            model_name='agenceuser',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agenceuser',
            constraint=models.UniqueConstraint(fields=('agent', 'agence'), name='affectation'),
        ),
    ]
