# Generated by Django 2.2.13 on 2020-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CNI', 'Carte Nationale d Identité'), ('Passeport', 'Passeport'), ('Permis', 'Permis de conduire')], max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('initiated_at', models.DateField()),
                ('expired_at', models.DateField()),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='Personne à prévenir')),
                ('contact_tel', models.CharField(blank=True, help_text='', max_length=50, verbose_name='Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
