# Generated by Django 2.2.13 on 2020-06-13 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20200612_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pieces_identites'),
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='identites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='contact_tel',
            field=models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='expired_at',
            field=models.DateField(verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='initiated_at',
            field=models.DateField(verbose_name='Emis le'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='N° matricule'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs'),
        ),
    ]
