# Generated by Django 2.2.13 on 2020-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_auto_20200614_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='contact_tel',
            field=models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(blank=True, help_text='90 00 00 00', max_length=50, unique=True, verbose_name='Téléphone'),
        ),
    ]
