# Generated by Django 2.2.13 on 2020-08-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0028_auto_20200808_2145'),
        ('utilisateurs', '0016_auto_20200715_2103'),
    ]

    operations = [
    ]
