# Generated by Django 2.2.13 on 2020-08-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0029_merge_20200809_1643'),
        ('utilisateurs', '0031_auto_20200816_1558'),
    ]

    operations = [
    ]
