# Generated by Django 2.2.13 on 2020-08-26 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0011_auto_20200826_1956'),
        ('utilisateurs', '0035_auto_20200826_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='agence',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True, max_length=500, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+228________', max_length=50, region=None, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='contact_tel',
            field=models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('CNI', 'Carte Nationale d Identité'), ('Passeport', 'Passeport'), ('Permis', 'Permis de conduire')], max_length=50)),
                ('reference', models.CharField(max_length=50, verbose_name='N° matricule')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pieces_identites')),
                ('initiated_at', models.DateField(verbose_name='Emis le')),
                ('expired_at', models.DateField(verbose_name='Expire le')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('contact_tel', models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agences.Agences')),
            ],
        ),
    ]
