# Generated by Django 2.2.13 on 2020-08-27 21:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0040_auto_20200826_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='contact_tel',
            field=models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identity',
            name='contact_tel',
            field=models.CharField(blank=True, help_text='', max_length=50, verbose_name='Tél'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+228________', max_length=50, region=None, unique=True, verbose_name='Téléphone'),
        ),
    ]
