# Generated by Django 2.2.13 on 2020-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agences',
            name='addresses',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
    ]
