# Generated by Django 2.2.13 on 2020-06-16 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agences', '0003_typevehicules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typevehicules',
            name='libelle',
            field=models.CharField(default=1, max_length=200, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modèle')),
                ('immatriculation', models.CharField(blank=True, max_length=200, null=True, verbose_name='immatriculation')),
                ('nb_place', models.IntegerField(blank=True, null=True, verbose_name='Nombre de places')),
                ('etat', models.TextField(blank=True, null=True, verbose_name='Etat du véhicule')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agences.TypeVehicules', verbose_name='Type de véhicules')),
            ],
        ),
    ]
