# Generated by Django 2.2.13 on 2020-06-16 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agences', '0004_auto_20200616_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicules',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
    ]
