# Generated by Django 2.2.13 on 2020-07-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0005_vehicules_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='immatriculation *'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agences.TypeVehicules', verbose_name='Type de véhicules *'),
        ),
    ]
