# Generated by Django 2.2.13 on 2020-08-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0010_auto_20200816_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicules',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vehicules',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeVehicules',
        ),
        migrations.DeleteModel(
            name='Vehicules',
        ),
    ]
